### ISSUE TITLE
cirq import not needed

### ISSUE THREAD

**Issue by alexandrupaler** [tbcdebug/QUEKO-benchmark#2]
The first line in CONNECTION.py imports cirq, but this is not needed

https://github.com/tbcdebug/QUEKO-benchmark/blob/84815582d850879690cbd4989165aa6cdac9b8cc/CONNECTION.py#L1

**Comment by qu-tan-um** [comment]
I need to import `GridQubit` from `cirq`

**Comment by alexandrupaler** [comment]
When using only Qiskit, for example, one needs cirq too. It would be possible to define the grids using `(col, row)` tuples, and then where the `GRID_QUBITS` are need to call `cirq.GridQubit(*(col,row))`

**Comment by qu-tan-um** [comment]
OK I get what you mean. I used this file in other projects as well, so I just add `import cirq` just in case in other projects cirq was not imported elsewhere.
